### ISSUE TITLE
Consider using string as key for bkDict type objects ?

### ISSUE THREAD

**Issue by sgmihai** [z-------------/nim-bencode#1]
I was thinking, wouldn't it be simpler to have string as bkDict keys, instead of BencodeObj ?
According to wikipedia: https://en.wikipedia.org/wiki/Bencode#Encoding_algorithm
"All keys must be byte strings and must appear in [lexicographical order](https://en.wikipedia.org/wiki/Lexicographical_order)."
For accessing a dict value now I have to write: myDecodedBeObj.d[Bencode("key")] instead of just myDecodedBeObj.d["key"]

Also, maybe publish to nimble directory ? There's already a nim-bencode library there, but it does not work correctly for all cases. And this one has clearer code

**Comment by z-------------** [comment]
I think I made bkDicts have BencodeObj keys in order to keep the library as flexible as possible (e.g. some exotic application might decide to use non-strings as bencode dictionary keys) (though I don't really remember; I wrote the library a long time ago).

How about if I added overloads that automatically convert the given string key to a bencode object, allowing you to do stuff like this?:

```nim
var b = Bencode({
  "interval": Bencode(1800),
  "complete": Bencode(20),
})
assert b.d["interval"] == Bencode(1800)
b.d["complete"] = Bencode(30)
```

Now that I'm looking at this library again, I'm thinking of changing BencodeObj to a regular value type instead of a `ref object`. What would you think about that?

**Comment by sgmihai** [comment]
I already modified the code locally to use strings instead of Bencode("string") for the dict keys. The overload you are talking about looks like the best option though.
About the ref vs value type, I am not really knowledgeable in this field and can't really grasp all the low level implications it would have. All I know is that with ref, assigning the dict to another variable, it won't to deep copy for the full tree when dereferncing.
