### ISSUE TITLE
Suggestion to add "b" prefix to encode/decode proc names

### ISSUE THREAD

**Issue by sgmihai** [z-------------/nim-bencode#2]
It seems to me that when reading the code .decode() .encode() appear to be too generic, and could mean anything. On the other hand bencode is very clear, can only mean one thing, as that is the name of the format. Same with bdecode. 
While I also like short names, I think they have to be readable first, and it's just 1 extra letter.

**Comment by sgmihai** [comment]
While at it, your commit that uses "b" shorthand template name for the bencode operations might break some code. For example, I had a foldl call which uses a and b variable names, and this conflicts with your "b". One letter is a bad idea anyway. mayb bE, or bEn, or bEnc ?

**Comment by z-------------** [comment]
You're right about decode and encode, I'll add a 'b' as you suggested.

I was hoping Nim's overload resolution/disambiguation would take care of any naming conflicts arising from the `b` template, but evidently not. I'll just remove it for now, since it's the same as the existing `Bencode` proc, and maybe add something like std/json's `%*` later.
